/**
 * Local-only PDF verification probe.
 *
 *   node scripts/pdf-check.mjs [port]
 *
 * react-pdf is the riskiest dependency this app ships: it needs a real Node
 * runtime, builds fonts at runtime and fetches the logo over the network. It is
 * the one thing that cannot be verified by `next build`, and it is exactly what
 * breaks silently on Vercel. So this drives the actual endpoint end to end:
 *
 *   1. no logo          -> font + layout path
 *   2. with a real PNG   -> react-pdf's runtime image fetch
 *   3. a long item list  -> multi-page + repeating table header
 *   4. RLS: a second account must get 404, never another user's PDF
 *
 * Writes the generated PDF to tmp/pdf-check/ so it can be opened by eye.
 * Creates a throwaway account and deletes it again.
 */
import { mkdir, writeFile } from "node:fs/promises";

const PORT = process.argv[2] || "3112";
const BASE = `http://localhost:${PORT}`;
const OUT_DIR = "tmp/pdf-check";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const PUBLISHABLE = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const SECRET = process.env.SUPABASE_SECRET_KEY;

if (!SUPABASE_URL || !PUBLISHABLE || !SECRET) {
  console.error("Missing Supabase env. Run via: npm run pdf:check");
  process.exit(1);
}

const { createClient } = await import("@supabase/supabase-js");
const admin = createClient(SUPABASE_URL, SECRET, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const results = [];
function check(name, pass, detail = "") {
  results.push({ name, pass });
  console.log(`  ${pass ? "PASS" : "FAIL"}  ${name}${detail ? `  ${detail}` : ""}`);
}

/** A tiny valid PNG (8x8, solid colour) so react-pdf does a real image fetch. */
const TINY_PNG = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAHUlEQVQoU2NkYGD4z8DAwMgABXAGNgGwAhWjY0cfAAAAABJRU5ErkJggg==",
  "base64",
);

async function signIn(email, password) {
  const anon = createClient(SUPABASE_URL, PUBLISHABLE, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
  const { data, error } = await anon.auth.signInWithPassword({ email, password });
  if (error) throw new Error(error.message);
  const cookieName = `sb-${SUPABASE_URL.replace(/^https?:\/\//, "").split(".")[0]}-auth-token`;
  const cookie = `${cookieName}=base64-${Buffer.from(
    JSON.stringify(data.session),
    "utf8",
  ).toString("base64url")}`;
  return { token: data.session.access_token, cookie };
}

async function createAccount(label) {
  const email = `pdfcheck-${label}-${Date.now()}@example.com`;
  const password = "PdfCheck12345!";
  const { data, error } = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: { full_name: `PDF Check ${label}` },
  });
  if (error) throw new Error(error.message);
  return { id: data.user.id, email, password };
}

const invoiceBody = (items, over = {}) => ({
  invoiceNumber: "",
  invoiceType: "standard",
  status: "draft",
  customer: {
    name: "Northwind Trading Co.",
    email: "ap@northwind.example",
    addressLine1: "14 Harbour Road",
    city: "Rotterdam",
    country: "Netherlands",
  },
  invoiceDate: new Date().toISOString().slice(0, 10),
  dueDate: new Date(Date.now() + 30 * 864e5).toISOString().slice(0, 10),
  currency: "USD",
  paymentTerms: "Net 30",
  items,
  discountType: "percent",
  discountValue: "5",
  shipping: "25",
  fees: "0",
  adjustment: "0",
  amountPaid: "0",
  template: "modern",
  design: {},
  notes: "Thank you for your business.",
  terms: "Late payment attracts interest at 4% above base rate.",
  footerText: "PDF Check Ltd — generated by the local verification probe.",
  paymentInstructions: "Bank transfer preferred.",
  paymentEnabled: false,
  paymentProvider: "manual",
  ...over,
});

const line = (n) => ({
  id: crypto.randomUUID(),
  name: `Consulting retainer — phase ${n}`,
  description:
    "Includes discovery workshops, implementation, review sessions, documentation and two rounds of revisions.",
  quantity: String(n),
  unitPrice: String(125 + n * 37.5),
  discount: n % 3 === 0 ? "5" : "0",
  tax: "20",
});

async function postJson(cookie, path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method: "POST",
    headers: { cookie, "content-type": "application/json" },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`HTTP ${res.status} on ${path}: ${text.slice(0, 300)}`);
  const parsed = JSON.parse(text);
  if (parsed?.ok === false) throw new Error(`API error on ${path}: ${JSON.stringify(parsed).slice(0, 300)}`);
  // every success body is { ok: true, data: ... }
  return parsed?.data ?? parsed;
}

async function postLogo(cookie, bytes, filename) {
  const form = new FormData();
  form.set("file", new File([bytes], filename, { type: "image/png" }));
  const res = await fetch(`${BASE}/api/logo`, { method: "POST", headers: { cookie }, body: form });
  const text = await res.text();
  if (!res.ok) throw new Error(`HTTP ${res.status} on /api/logo: ${text.slice(0, 300)}`);
  return JSON.parse(text);
}

/** Counts page objects in the rendered PDF and sanity-checks the file header. */
function inspect(buffer) {
  const head = buffer.subarray(0, 5).toString("latin1");
  const tail = buffer.subarray(-1024).toString("latin1");
  const body = buffer.toString("latin1");
  const pages = (body.match(/\/Type\s*\/Page[^s]/g) || []).length;
  return { head, pages, hasEof: tail.includes("%%EOF"), hasXref: body.includes("xref") };
}

async function main() {
  console.log(`\nPDF probe against ${BASE}\n`);
  console.log("react-pdf", (await import("@react-pdf/renderer/package.json", { with: { type: "json" } }).catch(() => ({ default: { version: "?" } }))).default.version, "\n");

  const account = await createAccount("main");
  const outsider = await createAccount("outsider");

  try {
    const { cookie } = await signIn(account.email, account.password);
    const outsiderAuth = await signIn(outsider.email, outsider.password);

    // ---- 1. a small invoice, no logo -------------------------------------
    console.log("→ creating a 2-item invoice…");
    const created = await postJson(cookie, "/api/invoices", invoiceBody([line(1), line(2)]));
    if (!created.invoice?.id) {
      console.log("    DEBUG create response:", JSON.stringify(created).slice(0, 500));
      throw new Error("create did not return an invoice id — cannot continue");
    }
    const id = created.invoice.id;
    check("invoice created via API", Boolean(id), id);

    console.log("→ POST /api/invoices/[id]/pdf (no logo)…");
    let res = await fetch(`${BASE}/api/invoices/${id}/pdf`, {
      method: "POST",
      headers: { cookie },
    });
    check("responds 200", res.status === 200, `got ${res.status}`);
    check(
      "content-type is application/pdf",
      res.headers.get("content-type")?.includes("application/pdf") ?? false,
      res.headers.get("content-type") || "",
    );
    let buffer = Buffer.from(await res.arrayBuffer());
    const small = inspect(buffer);
    check("valid PDF header", small.head === "%PDF-", `got "${small.head}"`);
    check("has xref table", small.hasXref);
    check("terminates with %%EOF", small.hasEof);
    check("non-trivial size", buffer.length > 3000, `${buffer.length} bytes`);
    check("at least one page", small.pages >= 1, `${small.pages} page(s)`);
    check(
      "attachment filename set",
      (res.headers.get("content-disposition") || "").includes("attachment"),
      res.headers.get("content-disposition") || "",
    );

    // ---- 2. with a logo, to force react-pdf's runtime image fetch --------
    console.log("\n→ uploading a logo to exercise the image fetch path…");
    await postLogo(cookie, TINY_PNG, "probe.png");
    res = await fetch(`${BASE}/api/invoices/${id}/pdf`, {
      method: "POST",
      headers: { cookie },
    });
    check("renders with a logo", res.status === 200, `got ${res.status}`);
    buffer = Buffer.from(await res.arrayBuffer());
    const withLogo = inspect(buffer);
    check("still a valid PDF with logo", withLogo.head === "%PDF-" && withLogo.hasEof, `${buffer.length} bytes`);

    // ---- 3. many items -> multi-page + repeating header ------------------
    console.log("\n→ 60 items to force pagination…");
    const big = await postJson(cookie, "/api/invoices", invoiceBody(Array.from({ length: 60 }, (_, i) => line(i + 1))));
    const bigId = big.invoice?.id;
    const started = Date.now();
    res = await fetch(`${BASE}/api/invoices/${bigId}/pdf`, {
      method: "POST",
      headers: { cookie },
    });
    const elapsed = Date.now() - started;
    buffer = Buffer.from(await res.arrayBuffer());
    const paged = inspect(buffer);
    check("renders 60 items", res.status === 200 && paged.pages >= 2, `${paged.pages} pages in ${elapsed} ms`);
    check("well inside maxDuration=60", elapsed < 30000, `${elapsed} ms`);

    // ---- 4. auth + RLS ---------------------------------------------------
    console.log("\n→ auth and RLS negative checks…");
    const anonRes = await fetch(`${BASE}/api/invoices/${id}/pdf`, { method: "POST" });
    check("rejects anonymous request", anonRes.status >= 400, `got ${anonRes.status}`);

    const otherRes = await fetch(`${BASE}/api/invoices/${id}/pdf`, {
      method: "POST",
      headers: { cookie: outsiderAuth.cookie },
    });
    check("other account gets 404, not a PDF", otherRes.status === 404, `got ${otherRes.status}`);

    // ---- keep an artifact to look at ------------------------------------
    await mkdir(OUT_DIR, { recursive: true });
    await writeFile(`${OUT_DIR}/small.pdf`, small.buffer ?? (await (async () => {
      const r = await fetch(`${BASE}/api/invoices/${id}/pdf`, { method: "POST", headers: { cookie } });
      return Buffer.from(await r.arrayBuffer());
    })()));
    await writeFile(`${OUT_DIR}/60-items.pdf`, buffer);

    console.log(`\nPDFs written to ${OUT_DIR}/ (small.pdf, 60-items.pdf)\n`);
  } finally {
    for (const a of [account, outsider]) {
      await admin.auth.admin.deleteUser(a.id).catch(() => {});
    }
  }

  const failed = results.filter((r) => !r.pass);
  console.log(
    failed.length
      ? `✖ ${failed.length}/${results.length} checks failed`
      : `✔ all ${results.length} PDF checks passed`,
  );
  process.exit(failed.length ? 1 : 0);
}

main().catch((error) => {
  console.error(`\n✖ ${error.message}\n`);
  process.exit(1);
});